config/routes.rb
Bakedfresh::Application.routes.draw do


  root to: 'store#index', as: 'store'
  get "errors/routing"

  resources :users
  
  
  resources :orders
  resources :customers
  resources :carts
  resources :charges

  resources :products do
    get :who_bought, on: :member
  end 



  resources :line_items



  resources :sessions, only: [:new, :create, :destroy]

  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  get 'sessions/signout'
  match '/cart', to: 'carts#index', via: 'get'
  
  match '/order', to: 'charges#new', via: 'get'

#Last route in routes.rb
  match '*a', :to => 'errors#routing', via: [:get, :post]
end

app/models/product.rb
class Product < ActiveRecord::Base
  default_scope order: 'title'
  
  has_many :line_items
  has_many :orders, through: :line_items

  before_save :update_it
  before_destroy :ensure_not_referenced_by_any_line_item
  

    def update_it 
      self.quantity = self.small + self.medium + self.large + self.xlarge + self.xxlarge 
    end


  private


    # def update_quantity
    #   total_quantity = self.small + self.medium + self.large + self.xlarge + self.xxlarge
    #   self.update_columns(quantity: total_quantity)
    # end



    def ensure_not_referenced_by_any_line_item
    	if line_items.empty?
    		return true
    	else
    		errors.add(:base, 'Line Items Present')
    		return false
    	end
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
 

  def index
    @cart = current_cart
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  def show
    @cart = current_cart
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  def new
    @cart = current_cart
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @product = Product.find(params[:id])
    
    respond_to do |format|
      if @product.update_attributes(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

private

  def product_params
    params.require(:product).permit(:title, :description, :image_url,
                    :thumb_nail, :price, :small, :medium, :large, 
                    :xlarge, :xxlarge, :quantity)
  end








end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br />
    <%= f.text_field :image_url %>
  </div>

  <div class="field">
    <%= f.label :thumb_nail %><br />
    <%= f.text_field :thumb_nail %>
  </div>

  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>


  <div class="field">
    <%= f.label :small %><br/>
    <%= f.text_field :small %>
  </div>

  <div class="field">
    <%= f.label :medium %><br/>
    <%= f.text_field :medium %>
  </div>


  <div class="field">
    <%= f.label :large %><br/>
    <%= f.text_field :large %>
  </div>


  <div class="field">
    <%= f.label :xlarge %><br/>
    <%= f.text_field :xlarge %>
  </div>

  <div class="field">
    <%= f.label :xxlarge %><br/>
    <%= f.text_field :xxlarge %>
  </div>

  Current Quantity: <%= @product.quantity %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Listing products</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Image url</th>
    <th>Price</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @products.each do |product| %>
  <tr>
    <td><%= product.title %></td>
    <td><%= product.description %></td>
    <td><%= image_tag(product.thumb_nail) %></td>
    <td><%= product.price %></td>
    <td><%= link_to 'Show', product %></td>
    <td><%= link_to 'Edit', edit_product_path(product) %></td>
    <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>







	<div class="main_shirt col-lg-6 col-lg-offset-3">

		<div class="main_image col-lg-6">
	  <%= image_tag(@product.image_url) %>
		</div>



		<div class="col-lg-4 col-lg-offset-1">


		<p class="price"> <%= number_to_currency(@product.price) %> </p>



		<%= form_tag( line_items_path(product_id: @product), method: "post",class: "size", remote: true) do %>
		
		<% if @product.small != 0 %>
		  <%= radio_button_tag(:size, "s", checked = true) %> Small </br>
		<% else %>
			<span style="text-decoration:line-through; padding-left:20px;"> Small</span> </br>
		<% end %>

		<% if @product.medium != 0 %>
		  <%= radio_button_tag(:size, "m") %> Medium </br>
    <% else %>
			<span style="text-decoration:line-through; padding-left:20px;"> Medium</span> </br>
		<% end %>

		<% if @product.large != 0 %>
		  <%= radio_button_tag(:size, "l") %> Large </br>
		<% else %>
			<span style="text-decoration:line-through; padding-left:20px;"> Large</span> </br>
		<% end %>

		<% if @product.xlarge != 0  %>
		  <%= radio_button_tag(:size, "xl") %> X-Large </br>
		<% else %>
			<span style="text-decoration:line-through; padding-left:20px;"> X-Large</span> </br>
		<% end %>


		<p class="chart">View Sizing Chart</p>


		</div>

	<div class="col-lg-12">
		<% if @product.quantity == 0 %>
		  <h3 class="soldout"> Sold Out </h3>
		<% else %>
		  <%= submit_tag("Add to Cart") %>
		<% end %>
	</div>

	<% end %>

	

</div>