config/routes.rb
Bakedfresh::Application.routes.draw do


  root to: 'store#index', as: 'store'
  get "errors/routing"

  resources :users
  
  
  resources :orders
  resources :customers
  resources :carts
  resources :charges

  resources :products do
    get :who_bought, on: :member
  end 



  resources :line_items



  resources :sessions, only: [:new, :create, :destroy]

  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  get 'sessions/signout'
  match '/cart', to: 'carts#index', via: 'get'
  
  match '/order', to: 'charges#new', via: 'get'

#Last route in routes.rb
  match '*a', :to => 'errors#routing', via: [:get, :post]
end

app/views/layouts/_checkout.html.erb
<% if @cart.respond_to? :line_items %>
	<% if !@cart.line_items.empty? %>
		<% if @page == "checkout" %>
		<div class="buttons">
			<%= button_to 'Continue Shopping', "/", action: 'store' %>

			<%= button_to 'Empty cart', @cart, method: :delete,
			   confirm: 'Are you sure you want to delete your cart?' %>

		</div>
				<form method="get" action="/order">
				    <button class="checkout"type="submit"><span>Continue Check Out</span></button>
				</form>
		<% else %>

				<form method="get" action="../carts/<%= @cart.id %>">
				    <button class="checkout"type="submit"><span>Check Out</span></button>
				</form>

		<%end%>
	<% end %>
<%end%>

app/views/layouts/_footer.html.erb
<nav class="navbar navbar-default navbar-fixed-bottom" role="navigation" class="footer" >
    	<%= link_to image_tag("footer.jpg", class: "footer"), "/", class: "footer" %>
</nav>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation"> 
	
		<div class="cart_total">
			<% if @cart %>
				<div id="cart">
				  <%= render(@cart)%>
				</div>
			<% end %>
		</div>

<div class="logo">
<%= link_to image_tag("Logo.png", :'data-mouseover' => "/logoover.png"), store_path %>
</div>






 <div id="checkout">
	 <%= render "layouts/checkout" %>
</div>


</nav>

app/views/layouts/_js.html.erb
<script type="text/javascript" charset="utf-8">
Stripe.setPublishableKey('<%= Rails.configuration.stripe[:publishable_key] %>');
 
var stripeResponseHandler = function(status, response) {
  var $form = $('#payment-form');
 
  if (response.error) {
    // Show the errors on the form
		$form.find('.payment-errors').text(response.error.message);
		$form.find('button').prop('disabled', false);
	} else {
		// token contains id, last4, and card type
		var token = response.id;
		// Insert the token into the form so it gets submitted to the server
		$form.append($('<input type="hidden" name="stripeToken" />').val(token));
		// and re-submit
		$form.get(0).submit();
	}
};
 
jQuery(function($) {

	$('#payment-form').submit(function(e) {
		var $form = $(this);
 
		// Disable the submit button to prevent repeated clicks
		$form.find('button').prop('disabled', true);
 
		Stripe.createToken($form, stripeResponseHandler);
 
		// Prevent the form from submitting with the default action
		return false;
	});


 $('img[data-mouseover]').hover(function() {
   $(this).data('_mouseover', $(this).attr('src'));
   $(this).attr('src', $(this).data('mouseover'));
 },function() {
   $(this).attr('src', $(this).data('_mouseover'));
});
  





});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bakedfresh</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "https://js.stripe.com/v2/", "https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js", "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<!-- start of body -->

	<%= render 'layouts/header' %>

	<% if signed_in? %>
	  </br></br></br>
	  YOU ARE SIGNED INNN
	<% end %>
	       
	<% if notice %>
	  <div id="notice"><%= notice %></div>
	<% end %>

	<div class="container">
	  <%= yield %>
	</div>

	<%= render 'layouts/footer' %>

<!-- end of body -->


	<%= render 'layouts/js' %>

<script type="text/javascript" charset="utf-8">


</script>

</body>
</html>
  